package com.myspace.poc_rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class validacionDTO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("num_validacion")
	private java.lang.Integer num_validacion;
	@org.kie.api.definition.type.Label("nom_validacion")
	private java.lang.String nom_validacion;

	public validacionDTO() {
	}

	public java.lang.Integer getNum_validacion() {
		return this.num_validacion;
	}

	public void setNum_validacion(java.lang.Integer num_validacion) {
		this.num_validacion = num_validacion;
	}

	public java.lang.String getNom_validacion() {
		return this.nom_validacion;
	}

	public void setNom_validacion(java.lang.String nom_validacion) {
		this.nom_validacion = nom_validacion;
	}

	public validacionDTO(java.lang.Integer num_validacion,
			java.lang.String nom_validacion) {
		this.num_validacion = num_validacion;
		this.nom_validacion = nom_validacion;
	}

}